# ***CHAPTER 3*** :- ***ARRAY CREATION ROUTINE***

#WHAT IS ARRAY CREATION ROUTINE ?
**ANSWER**:- ARRAY CREATION ROUTINES IN PYTHON ARE BUILT-IN FUNCTIONS PROVIDED BY THE NUMPY LIBRARY THAT HELP TO CREATE ARRAYS IN DIFFERENT WAYS.

THESE ROUTINES ALLOW US TO CREATE ARRAYS FILLED WITH SPECIFIC VALUES, ZEROS, ONES, RANGES OF NUMBERS, OR EVENLY SPACED VALUES WITHOUT WRITING LONG CODE.

In [ ]:
import numpy as np

## ***1)EMPTY*** :- IT CREATES AN UNTITELIZED ARRAY OF SPECIFIED SHAPE AND DATA TYPE.

In [ ]:
w=np.empty(6)

In [ ]:
print(w)

[ 5.23602837e-315  0.00000000e+000 -6.67959941e+232  2.56621039e-308
  6.47538572e-308  4.66851194e-300]


In [ ]:
w.reshape(3,2)

array([[ 5.23602837e-315,  0.00000000e+000],
       [-6.67959941e+232,  2.56621039e-308],
       [ 6.47538572e-308,  4.66851194e-300]])

In [ ]:
p=np.empty([3,2],dtype=int)

In [ ]:
p

array([[          1059783940,                    0],
       [-1133355574716327279,     5194067646415107],
       [   11056762929152000,   128637372707841992]])

## **2)ARANGE**:- IT IS AN ARRAY CREATION ROUTINE IN THE NUMPY LIBRARY THAT IS USED TO CREATE AN ARRAY WITH A SEQUENCE OF NUMBERS.


---



IT STARTS FROM ONE NUMBER AND STOPS BEFORE ANOTHER NUMBER.
YOU CAN ALSO CHOOSE THE GAP (STEP) BETWEEN THE NUMBERS.

In [ ]:
v=np.arange(2,21,2).reshape(5,2)

In [ ]:
v

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

## ***3)ZEROS*** :- IT RETURN A NEW ARRAY OF A SPECIFIED SIZE FILLED WITH ZERO.

In [ ]:
q=np.zeros(6)

In [ ]:
q

array([0., 0., 0., 0., 0., 0.])

In [ ]:
r=np.zeros([6],dtype=int).reshape(3,2)

In [ ]:
r

array([[0, 0],
       [0, 0],
       [0, 0]])

## ***4)ONES*** :- IT RETURN THE NEW ARRAY OF SPECIFIED SIZE FILLED WITH ONES.

In [ ]:
m=np.ones([4,5],dtype=int)

In [ ]:
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## ***5)EYE*** :- EYE ROUTINE CAN RETURN THE IDENTITY MATRIX.

In [ ]:
l=np.eye(1)

In [ ]:
l

array([[1.]])

In [ ]:
o=np.eye(2)

In [ ]:
o

array([[1., 0.],
       [0., 1.]])

In [ ]:
q=np.eye(3)

In [ ]:
q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ***6)LINSPACE*** :-THIS FUNCTION IS SIMILAR TO RANGE FUNCTION IN THIS FUNCTION INSTED OF STOP SIZE THE NUMBER OF EVENLY  SPACED VALUES BETWEEN THE INTERVAL IS SPECIFIED.

In [ ]:
K=np.linspace(0,1,50)

In [ ]:
K

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
n=np.linspace(10,20,5)

In [ ]:
n

array([10. , 12.5, 15. , 17.5, 20. ])

# ****CASE STUDY***

In [ ]:
X=np.zeros([10,10])

In [ ]:
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
X.shape[1]

10

In [ ]:
le =X.shape[1]

In [ ]:
le

10

In [ ]:
for i in range(le):
  X[1]

In [ ]:
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])