# ***CHAPTER  :- 1***

#1)WHAT IS NUMPY ?

NUMPY (NUMERICAL PYTHON) IS A POWERFUL PYTHON LIBRARY USED FOR NUMERICAL AND SCIENTIFIC COMPUTING.
IT PROVIDES SUPPORT FOR ARRAYS, MATRICES, AND MANY MATHEMATICAL FUNCTIONS TO PERFORM FAST CALCULATIONS.

NUMPY IS THE FOUNDATION OF DATA SCIENCE, MACHINE LEARNING, AND SCIENTIFIC COMPUTING IN PYTHON BECAUSE IT MAKES WORKING WITH LARGE AMOUNTS OF DATA EASY AND EFFICIENT.

In [ ]:
import numpy as np

#2) WHAT IS ARRAY() ?
ARRAY() IS A FUNCTION IN THE NUMPY LIBRARY THAT IS USED TO CREATE AN ARRAY FROM A LIST, TUPLE, OR OTHER SEQUENCE.
IT CONVERTS NORMAL PYTHON DATA STRUCTURES INTO NUMPY ARRAYS WHICH ARE FASTER AND MORE POWERFUL FOR NUMERICAL CALCULATIONS.

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])

#3)WHAT IS shape() IN NUMPY ?

shape IS AN ATTRIBUTE (NOT A FUNCTION) IN NUMPY THAT TELLS THE SIZE OR DIMENSIONS OF AN ARRAY.

IT SHOWS HOW MANY ROWS AND COLUMNS (OR LEVELS) ARE PRESENT IN THE ARRAY.
IN SIMPLE WORDS, IT DESCRIBES THE STRUCTURE OF THE ARRAY.

In [ ]:
a.shape

(2, 3)

#4)WHAT IS size() IN NUMPY

size IS AN ATTRIBUTE IN NUMPY THAT RETURNS THE TOTAL NUMBER OF ELEMENTS PRESENT IN AN ARRAY — REGARDLESS OF ITS DIMENSIONS.

In [ ]:
a.size

6

#5)WHAT IS reshape() IN NUMPY
reshape() IS A FUNCTION IN NUMPY THAT IS USED TO CHANGE THE SHAPE (STRUCTURE) OF AN EXISTING ARRAY WITHOUT CHANGING ITS DATA.

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a.shape=(3,2)

In [ ]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


# 6) WHAT IS TRANSPOSE() ?
TRANSPOSE() IS A FUNCTION IN NUMPY THAT IS USED TO FLIP OR REVERSE THE DIMENSIONS OF AN ARRAY.

IN SIMPLE WORDS, IT CHANGES ROWS INTO COLUMNS AND COLUMNS INTO ROWS IN A 2D ARRAY.

FOR HIGHER-DIMENSION ARRAYS, IT REARRANGES THE AXES ACCORDING TO SPECIFIED ORDER.

In [ ]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a.size

8

In [ ]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a.shape=(4,2)

In [ ]:
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [ ]:
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a.size

12

In [ ]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a.shape=(4,3)

In [ ]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a.T



array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a=np.arange(1,7).reshape(2,3)

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
x=np.arange(7,13).reshape(2,3)

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


# 7)WHAT IS CONCATENATE() IN NUMPY ?

CONCATENATE() IS A FUNCTION IN NUMPY THAT IS USED TO JOIN (COMBINE) TWO OR MORE ARRAYS INTO A SINGLE ARRAY.

IT PUTS ARRAYS END TO END ALONG A SPECIFIED AXIS —
LIKE JOINING STRINGS OR SENTENCES TOGETHER, BUT HERE IT JOINS NUMPY ARRAYS.

In [ ]:
z=np.concatenate((x,a))

In [ ]:
print(z)

[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


# 8)WHAT IS HSTACK() IN NUMPY ?

HSTACK() IS A FUNCTION IN NUMPY THAT IS USED TO JOIN (STACK) ARRAYS HORIZONTALLY,
MEANING — IT COMBINES ARRAYS SIDE BY SIDE (COLUMN-WISE).

THE LETTER ‘H’ IN HSTACK STANDS FOR HORIZONTAL.

In [ ]:
m=np.hstack((x,a))

In [ ]:
print(m)

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]


In [ ]:
q=np.array([1,2,3,4,5,6])

# 9)WHAT IS VSTACK() IN NUMPY ?

VSTACK() IS A FUNCTION IN NUMPY THAT IS USED TO JOIN (STACK) ARRAYS VERTICALLY,
MEANING — IT COMBINES ARRAYS ONE ON TOP OF ANOTHER (ROW-WISE).

THE LETTER ‘V’ IN VSTACK STANDS FOR VERTICAL.

In [ ]:
np.vstack(q)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
print(q)

[1 2 3 4 5 6]


In [ ]:
ap=np.arange(1,7)

In [ ]:
array=([1,2,3,4,5,6])

#10)WHAT IS APPEND() IN NUMPY ?

APPEND() IS A FUNCTION IN NUMPY THAT IS USED TO ADD (APPEND) NEW VALUES OR ARRAYS TO AN EXISTING ARRAY AND RETURN A NEW ARRAY.

IT DOES NOT CHANGE THE ORIGINAL ARRAY — IT CREATES A NEW ONE WITH THE ADDED ELEMENTS.

In [ ]:
ap=np.append(ap,[7,8,9])

In [ ]:
print(ap)

[1 2 3 4 5 6 7 8 9]


In [ ]:
mn=np.array([2,3,4,5])

#11)WHAT IS INSERT() IN NUMPY ?

INSERT() IS A FUNCTION IN NUMPY THAT IS USED TO INSERT (ADD) VALUES INTO AN ARRAY AT A SPECIFIC POSITION OR INDEX.

IT CREATES A NEW ARRAY WITH THE INSERTED VALUES —
THE ORIGINAL ARRAY DOES NOT CHANGE.

In [ ]:
mn=np.insert(mn,0,1)

In [ ]:
print(mn)

[1 2 3 4 5]


In [ ]:
mn=np.insert(mn,0,7)

In [ ]:
print(mn)

[7 1 2 3 4 5]


#12)WHAT IS DELETE() IN NUMPY ?

DELETE() IS A FUNCTION IN NUMPY THAT IS USED TO REMOVE (DELETE) ELEMENTS, ROWS, OR COLUMNS FROM AN EXISTING ARRAY.

IT DOES NOT CHANGE THE ORIGINAL ARRAY —
INSTEAD, IT RETURNS A NEW ARRAY WITH THE SPECIFIED ELEMENTS DELETED.

In [ ]:
mn=np.delete(mn,0)

In [ ]:
print(mn)

[1 2 3 4 5]
