# ***CHAPTER 2***
---



# **TOPIC 1 :-SLICING AND INDEXING IN ARRAY**


---



#1)WHAT IS INDEXING IN NUMPY ?

INDEXING MEANS ACCESSING (PICKING) ONE OR MORE ELEMENTS FROM AN ARRAY BY THEIR POSITION (INDEX NUMBER).


---



#2)WHAT IS SLICING IN NUMPY ?

SLICING MEANS TAKING A PART (SUBSET) OF AN ARRAY.
IT LETS YOU CUT A PORTION OF THE ARRAY USING A RANGE OF INDEXES.

In [ ]:
import numpy as np

#3)WHAT IS array() IN NUMPY ?

array() IS A FUNCTION IN THE NUMPY LIBRARY THAT IS USED TO CREATE AN ARRAY FROM A LIST, TUPLE, OR OTHER SEQUENCE.

In [ ]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
x= np.array([1,2,3,4,5,6])

In [ ]:
x

array([1, 2, 3, 4, 5, 6])

#4)WHAT IS ndim() IN NUMPY ?

ndim() IS AN ATTRIBUTE (NOT A FUNCTION) IN THE NUMPY LIBRARY THAT IS USED TO FIND THE NUMBER OF DIMENSIONS (AXES) OF A NUMPY ARRAY.

In [ ]:
x.ndim

1

In [ ]:
x.shape

(6,)

In [ ]:
z=np.arange(1,7)

In [ ]:
z

array([1, 2, 3, 4, 5, 6])

In [ ]:
z.ndim

1

In [ ]:
z[0]

np.int64(1)

In [ ]:
z[1]

np.int64(2)

In [ ]:
z[2]

np.int64(3)

In [ ]:
z[3]

np.int64(4)

In [ ]:
z[4]

np.int64(5)

In [ ]:
z[5]

np.int64(6)

In [ ]:
y=np.arange(1,21).reshape(5,4)

In [ ]:
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
y[1]

array([5, 6, 7, 8])

In [ ]:
y[0: :3]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
y[1:4:2,2: :1]

array([[ 7,  8],
       [15, 16]])

In [ ]:
y[0:4:1,0:3:1]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
y[2: :-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
y[4:0:-1]

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [ ]:
y[4:1:-1,3: :1]

array([[20],
       [16],
       [12]])

In [ ]:
y[1::1,0::3]

array([[ 5,  8],
       [ 9, 12],
       [13, 16],
       [17, 20]])

# ***TOPIC 2*** :- ***BROADCASTING IN AN ARRAY***


---



#5)WHAT IS BROADCASTING IN NUMPY ARRAYS ?
BROADCASTING ALLOWS NUMPY TO DO OPERATIONS BETWEEN ARRAYS OF DIFFERENT SIZES BY “STRETCHING” THE SMALLER ONE TO FIT THE BIGGER ONE.

In [ ]:
M= np.arange(1,7)

In [ ]:
M[2]=55

In [ ]:
print(M)

[ 1  2 55  4  5  6]


In [ ]:
M[ : :2]=15

In [ ]:
print(M)

[15  2 15  4 15  6]


In [ ]:
M[1::2]=0

In [ ]:
print(M)

[15  0 15  0 15  0]


In [ ]:
N=np.arange(1,21).reshape(4,5)

In [ ]:
N

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
N[::4]=55

In [ ]:
N

array([[55, 55, 55, 55, 55],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
N[::1,3:4:1]=0.25

In [ ]:
N

array([[55, 55, 55,  0, 55],
       [ 6,  7,  8,  0, 10],
       [11, 12, 13,  0, 15],
       [16, 17, 18,  0, 20]])