# ***CHAPTER :- 4***

# ***TOPIC 1 :- ARRAY SELECTION***

In [ ]:
import numpy as np


In [ ]:
x=np.arange(1,11)

In [ ]:
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
y=list(range(1,11))

In [ ]:
y

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
x*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [ ]:
y*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
x>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
mask=x>5

In [ ]:
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
x[mask]

array([ 6,  7,  8,  9, 10])

In [ ]:
a=np.array(['raj','roy','van','raj'])

In [ ]:
a!='raj'

array([False,  True,  True, False])

In [ ]:
MASK=a!='raj'

In [ ]:
MASK

array([False,  True,  True, False])

In [ ]:
a[MASK]

array(['var', 'var'], dtype='<U3')

In [ ]:
b=a!='raj'

In [ ]:
a[b]

array(['roy', 'van'], dtype='<U3')

In [ ]:
a[b]='ved'

In [ ]:
a

array(['raj', 'ved', 'ved', 'raj'], dtype='<U3')

In [ ]:
a[b]='varun'

In [ ]:
a

array(['raj', 'var', 'var', 'raj'], dtype='<U3')